In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0],a[1]

(1, 2)

In [5]:
import time 
import sys

In [6]:
b=range(1000)
print(sys.getsizeof(5)*len(b))


28000


In [7]:
c=np.arange(200)
sys.getsizeof(c)
print(c.size*c.itemsize)

800


In [8]:
size=10000


In [9]:
l1=range(size)
l2=range(size)
A1=np.arange(size)
A2=np.arange(size)


In [10]:
import time
import numpy as np

# Define lists for Python list timing
l1 = list(range(10000))
l2 = list(range(10000))

# Measure time for Python list
start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("Python list took", (time.time() - start) * 1000, "ms")

# Define NumPy arrays
arr1 = np.arange(10000)
arr2 = np.arange(10000)

# Measure time for NumPy operation
start = time.time()
arr_sum = arr1 + arr2  # Element-wise addition
print("Python NumPy took", (time.time() - start) * 1000, "ms")  # Correct timing


Python list took 0.0 ms
Python NumPy took 0.0 ms


In [12]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a.ndim

2

In [14]:
a.itemsize

4

In [15]:
a.shape

(3, 2)

In [17]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [18]:
a.itemsize

8

In [19]:
a.shape

(3, 2)

In [22]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex128)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
l=range(5)
l

range(0, 5)

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
print("Concatinating")
print(np.char.add(['hello','hii'],['ravi','kiran']))

Concatinating
['helloravi' 'hiikiran']


In [32]:
print("multiplying")
print(np.char.multiply('hello',5))

multiplying
hellohellohellohellohello


In [35]:
print(np.char.center('hello',20,fillchar='.'))

.......hello........


In [36]:
print(np.char.capitalize('ravikiran'))

Ravikiran


In [38]:
print(np.char.title('welcome to upskill'))

Welcome To Upskill


In [39]:
print(np.char.lower("RAVIKIRAN"))

ravikiran


In [40]:
print(np.char.upper("ssss"))


SSSS


In [41]:
print(np.char.split("Hii I'm ravikiran"))

['Hii', "I'm", 'ravikiran']


In [43]:
print(np.char.splitlines("Hii \nI'm ravikiran"))

['Hii ', "I'm ravikiran"]


In [ ]:
np.char.join([';'])

['Hii  Im aravikiran']
